AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "vendor/bundle/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "db/**/*"
    - "db/schema.rb"
    - "log/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "config/**/*"
    - "*file"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20