default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  database: <%= ENV['DATABASE_DBNAME'] %>

development:
  <<: *default
  database: todos-dev

test:
  <<: *default
  database: todos-test

production:
  <<: *default
